name: authentication_repository


environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4  

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.3.18
  google_sign_in: ^5.3.2
  